### PR TITLE
[#76] Moved functionality from Artifact class to ArtifactCommand class.

### LINKED ISSUE #76: Move functionality from `Artifact` class to  `ArtifactCommand` class
#42 allows us to further improve the architecture of this package.

BLOCKED by #64

---

We now need to reconcile `Artifact` and `ArtifactCommand` classes.

This ticket is about moving the functionality of the `Artifact` to `ArtifactCommand`.

Please note that there is be a follow-up ticket to replace the logger with `monolog`.

## Solution direction.

1. Merge the functionality of `Artifact` to `ArtifactCommand`. The `Artifact::artifact()` should become `ArtifactCommand::processArtifact()` and be called from `ArtifactCommand::execute()`.

2. Update `ArtifactCommand::execute() to correctly return exit codes on exception.
The code should look like:

```php
  protected function execute(InputInterface $input, OutputInterface $output): int {
    $this->logger = self::logInit($output);

    $this->checkRequirements();

    try {
      $this->processArtifact();
    }
    catch (\Exception $e) {
      $output->writeln('<error>' . $e->getMessage() . '</error>');

      return Command::FAILURE;
    }

    return Command::SUCCESS;
  }
```

### PR DESCRIPTION
**Pull request by tannguyen04**
## Checklist before requesting a review

closes #76 

- [x] I have formatted the subject to include ticket number as `[#123] Verb in past tense with dot at the end.`
- [x] I have added a link to the issue tracker
- [x] I have provided information in `Changed` section about WHY something was done if this was not a normal implementation
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run new and existing relevant tests locally with my changes, and they passed
- [x] I have provided screenshots, where applicable

## Changed

1.

### CODE REVIEW

File: src/app.php [hunk 1]
```diff
@@ -6,11 +6,16 @@
...
 
 use DrevOps\GitArtifact\Commands\ArtifactCommand;
+use DrevOps\GitArtifact\GitArtifactGit;
 use Symfony\Component\Console\Application;
+use Symfony\Component\Filesystem\Filesystem;
 
 $application = new Application();
 
-$command = new ArtifactCommand();
+$git = new GitArtifactGit();
```
Comment (AlexSkrypnyk) [inline src/app.php:15]: please move this into the ArtifactCommand class

please do not modify this file - it is a standard entrypoint

**Review by AlexSkrypnyk — CHANGES_REQUESTED** [review]

File: src/app.php (hunk 1 above)
Comment (tannguyen04) [reply src/app.php]: Hi @AlexSkrypnyk 
I have reverted to standard entry point.

**Review by AlexSkrypnyk — APPROVED** [review]
